# Generated by Django 4.2.1 on 2023-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app1", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="service_request_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[("C", "COMPLETED"), ("P", "PENDING")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
